package io.oz.syntier.serv;

import java.util.HashMap;

import io.odysz.anson.Anson;
import io.odysz.anson.AnsonField;

/**
 * If the web pages are not static and needs some data layer
 * configurations, use this to feed data to callback handler,
 * e.g. {@link IResUpdater} .
 * 
 * This is a business data of {@link IResUpdater#onStartup(WebConfig)},
 * so no need to care about if not implementing the interface.
 * 
 * (This class should actually locate in an external jar or be generated by IDE)
 * 
 * @since 0.1.4
 */
public class ExternalHosts extends Anson {

	public String host;
	public String localip;

	public HashMap<String, String> syndomx;
	public HashMap<String, String> resources;

	/**
	 * @deprecated Not used yet, by redundant design?
	 */
	@AnsonField(valType="[Ljava.lang.Object;")
	public HashMap<String, String[]>synodesetups;
	
	public ExternalHosts() {
		syndomx = new HashMap<String, String>();
		resources = new HashMap<String, String>();
	}
}
